# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652ad6980491d5d74ba6591a27084b2f5308d9ebc9b13ebf827e8c554fb35ab6b05cbe5cff0e7eab33622b49ec984a976e10b9b002a6b07ace490b65dee95b9a

test:
  secret_key_base: 8b930eb92f1775b415f5ddc1e10d00a734b09f50c791b0112647cd44ef347373f9c0bbb6562f53881706b362d3ad4b4f12e321511e104cd11dfeaf3d2368a7c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
